### ISSUE TITLE
Border token type docs

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/plugin-docs#40]
**Related issue:** https://github.com/six7/figma-tokens/issues/1266

**Name doc:** Border tokens

**Video walk through:** 
**Doc:**

**Comment by six7** [comment]
```
Type: 'border'
Name: 'Border'
Value: {
         color: ColorToken: color token input or reference to a color token | Placeholder: 'Border color',
         width: dimension token input or a reference to a borderWidth or dimension token | Placeholder: 'Border width'
         style: StrokeStyle | Placeholder: 'solid | dashed'
       }
```

should be a good basis for the Docs

I'll create a video explaining how to
- create them
- apply them
- use in combination with other tokens (eg borderWidth, color)
- what to expect next (borderStyle)
