### ISSUE TITLE
Sync problem with Azure DevOps

### ISSUE THREAD

**Issue by XmlmXmlmX** [tokens-studio/plugin-docs#67]
Hi, i have a problem with syncing to Azure DevOps.
I'm also confused about the parameters. Should the organization URL contain the project?

If I enter the following parameters, i get this message:

![image](https://user-images.githubusercontent.com/677165/219325626-5a6009a2-c70b-404d-9af4-fe731373cbcb.png)

> There is no branch

If i try it without project name:

![image](https://user-images.githubusercontent.com/677165/219325993-d4c78af8-9c89-4889-abe4-ae8f6dc8af45.png)

> Contents don't pass schema validation

I'm not sure what's wrong.

**Comment by six7** [comment]
Is the repository initialized? Make sure there's some contents in there, that could be an issue. As for a project name: I think it depends on the type of project / organization. Sometimes it's required, sometimes not. I'm not entirely sure on it, I don't use ADO myself.

**Comment by hylmar** [comment]
@XmlmXmlmX have you solved this? I'm running into the same issue.

**Comment by XmlmXmlmX** [comment]
@hylmar, no I didn't. In the meantime I switched to Figma Variables.
