### ISSUE TITLE
Link to Figma Plugin Helpers tool 404s

### ISSUE THREAD

**Issue by iamnbutler** [tokens-studio/plugin-docs#78]
The link in this section 404s: https://docs.tokens.studio/contributing/shared-data#figma-plugin-helpers

This is the provided link: https://www.npmjs.com/package/@tokens-studio/figma-plugin-helpers

I looked around to try to find the correct link to submit a PR but I couldn't find what it was trying to link to either.

**Comment by six7** [comment]
Thanks for raising this!

The real link is https://www.npmjs.com/package/@six7/figma-tokens-helpers

I'll probably re-publish this plugin with a dedicated repo once I find time for it, we have never migrated it over to the org account but seem to have changed the URL in the docs
